### ISSUE TITLE
HTTP://1.1 401 Unauthorised

### ISSUE THREAD

**Issue by JordiCorbilla** [JordiCorbilla/FlickrPhotoStats#1]
Hi Jordi

I am trying to use your App, but get an error HTTP://1.1 401 Unauthorised after I have entered my new API Key and Secret just for this app and when I press the button test RES login I get the 401 error.

Any ideas please?

Regards
Graham

**Comment by JordiCorbilla** [comment]
Hi Graham,

What version are you using?
Are you using the 32bits or 64bits version?

Regards,
Jordi

**Comment by grahamrivers** [comment]
Hi Jordi

I am trying the x64 version. I have tried this on Windows 7, Windows 8.1 and Windows 10 Preview all x64 versions and get the same 401 error.

Regards
Graham

**Comment by JordiCorbilla** [comment]
Hi Graham,

You need to authenticate the application first. But it's only needed if you want to include your picture in groups, etc. Just add the details for you APIkey and secret and add a photo to the list, it should pick it up straight away. Or go to the Photo List section (add your user Id) and retrieve the list. Once you've got the list, add the items to the main list and that's it.

Regards,
Jordi

**Comment by grahamrivers** [comment]
Hi Jordi
I had already tried that according to the instructions on the web but it does not allow me to. The web browser section is blank and the Authenticate button is not active. See below:

http://old.moulsford.com/files/auth.jpg 

I have entered my API key and secret, then I try to authenticate. but nothing happens.

I'm stuck!
Regards
Graham

**Comment by JordiCorbilla** [comment]
Hi Graham,

Have you got installed any version of IE? The applications calls the underlying IE installed on your machine. Go to Internet properties also and click on "Use SSL 2.0", "Use SSL 3.0", "Use TLS 1.0", "Use TLS1.1" and "Use TLS 1.2" options.

Regards,
Jordi

**Comment by grahamrivers** [comment]
Hi Jordi

Yes, IE11 is installed SSL 2.0 and SSL 3.0 were not selected so I have selected them and tried again, still no authentication and error 401 still persists.

http://www.grageo.co.uk/files/Capture.PNG 

I just do not know what it can be.

Best regards
Graham

From:  Jordi Corbilla
Reply-To:  JordiCorbilla/FlickrPhotoStats
Date:  Tuesday, 7 July 2015 22:13
To:  JordiCorbilla/FlickrPhotoStats
Cc:  Graham Rivers
Subject:  Re: [FlickrPhotoStats] HTTP://1.1 401 Unauthorised (#1)


Hi Graham,

Have you got installed any version of IE? The applications calls the underlying IE installed on your machine. Go to Internet properties also and click on "Use SSL 2.0", "Use SSL 3.0", "Use TLS 1.0", "Use TLS1.1" and "Use TLS 1.2" options.

Regards,
Jordi

**Comment by JordiCorbilla** [comment]
Hi Graham,

What about clicking on the "Navigate to URL" button? Do you get anything displayed there at all? This behaviour is weird as I've tested this under Windows 7 and Windows Server 2012 and it works like a charm. Without this being displayed, you won't be able to authenticate the application as it needs to get a response from Flickr for authorisation.

Regards,
Jordi

**Comment by JordiCorbilla** [comment]
Hi Graham,

Can you try with the 32bits version?

Regards,
Jordi

**Comment by grahamrivers** [comment]
Hi Jordi

Thanks for sticking with this.

I have success. Below is what I have done this morning.

I built a brand new Virtual PC running Windows 7 Pro x86. Downloaded your v4.3rc x86 version.

Went through the authentication routine without problem.

Many many thanks for not giving up on me.

Very appreciated.
Graham

From:  Jordi Corbilla
Reply-To:  JordiCorbilla/FlickrPhotoStats
Date:  Saturday, 11 July 2015 13:44
To:  JordiCorbilla/FlickrPhotoStats
Cc:  Graham Rivers
Subject:  Re: [FlickrPhotoStats] HTTP://1.1 401 Unauthorised (#1)


Hi Graham,

Can you try with the 32bits version?

Regards,
Jordi

**Comment by JordiCorbilla** [comment]
Hi Graham,

Excellent news then! I hope you enjoy the app!

Any questions, please ask :)

Regards,
Jordi

**Comment by grahamrivers** [comment]
Hi Jordi

Sorry, almost successful, seems to be connected ok now, log show me logging in etc. All the screens are blank, do they populate automatically or do I have to add my photo stream/photos etc manually??

I tried pressing the Batch Update button but get this error.

Best regards
Graham






From:  Jordi Corbilla
Reply-To:  JordiCorbilla/FlickrPhotoStats
Date:  Saturday, 11 July 2015 13:44
To:  JordiCorbilla/FlickrPhotoStats
Cc:  Graham Rivers
Subject:  Re: [FlickrPhotoStats] HTTP://1.1 401 Unauthorised (#1)


Hi Graham,

Can you try with the 32bits version?

Regards,
Jordi

**Comment by JordiCorbilla** [comment]
Hi Graham,

Go to Photo List tab, add your user Id and press "get entire list". Then you'll see your list of photos. Then press "Add items to the main list" and your main list will be automatically populated.

Then you can use the "batch update" button every day to keep track of your stacks. 

You are almost there :)

Regards,
Jordi

**Comment by grahamrivers** [comment]
Jordi

Each time I try and press “Add items to the main list” it adds one and then errors:

If I then press Get entire list and Add items to main list it does the same, it adds the first item (being the next item) and errors thus only adding 1 photo at a time.

Regards
Graham



From:  Jordi Corbilla
Reply-To:  JordiCorbilla/FlickrPhotoStats
Date:  Sunday, 12 July 2015 13:03
To:  JordiCorbilla/FlickrPhotoStats
Cc:  Graham Rivers
Subject:  Re: [FlickrPhotoStats] HTTP://1.1 401 Unauthorised (#1)


Hi Graham,

Go to Photo List tab, add your user Id and press "get entire list". Then you'll see your list of photos. Then press "Add items to the main list" and your main list will be automatically populated.

Then you can use the "batch update" button every day to keep track of your stacks. 

You are almost there :)

Regards,
Jordi

**Comment by JordiCorbilla** [comment]
Hi Graham,

What error do you get?

Regards,
Jordi

**Comment by grahamrivers** [comment]
Hi Jordi, these two below.


From:  Jordi Corbilla
Reply-To:  JordiCorbilla/FlickrPhotoStats
Date:  Sunday, 12 July 2015 20:32
To:  JordiCorbilla/FlickrPhotoStats
Cc:  Graham Rivers
Subject:  Re: [FlickrPhotoStats] HTTP://1.1 401 Unauthorised (#1)


Hi Graham,

What error do you get?

Regards,
Jordi

**Comment by JordiCorbilla** [comment]
Hi Graham,

Sorry, i didn't get the errors. Could you please send the screenshots again?

Regards,
Jordi

**Comment by grahamrivers** [comment]
Hi Jordi

Sending this time as an attachment, hopefully it will come through.

Graham



From:  Jordi Corbilla
Reply-To:  JordiCorbilla/FlickrPhotoStats
Date:  Monday, 13 July 2015 20:50
To:  JordiCorbilla/FlickrPhotoStats
Cc:  Graham Rivers
Subject:  Re: [FlickrPhotoStats] HTTP://1.1 401 Unauthorised (#1)


Hi Graham,

Sorry, i didn't get the errors. Could you please send the screenshots again?

Regards,
Jordi

**Comment by JordiCorbilla** [comment]
Hi Graham,

Sorry but it seems that they get filtered out by gidhub as it's a notification service.

Regards,
Jordi

**Comment by JordiCorbilla** [comment]
Hi Graham,

Just make sure you are running the application with enough permissions.

Regards,
Jordi

**Comment by JordiCorbilla** [comment]
Hi Graham,

Just get version 4.4 and see if this solves your problems. You'll find it available now.

Regards,
Jordi

**Comment by grahamrivers** [comment]
Hi Jordi

Grabbed 4.4 x86. Still get the out of range error when loading saved config. Also with 4.4 I get API KEY cannot be empty when clicking on list photos. :(

Graham

From:  Jordi Corbilla
Reply-To:  JordiCorbilla/FlickrPhotoStats
Date:  Monday, 13 July 2015 21:40
To:  JordiCorbilla/FlickrPhotoStats
Cc:  Graham Rivers
Subject:  Re: [FlickrPhotoStats] HTTP://1.1 401 Unauthorised (#1)


Hi Graham,

Just get version 4.4 and see if this solves your problems. You'll find it available now.

Regards,
Jordi

**Comment by JordiCorbilla** [comment]
Hi Graham,

Options tab needs to be populated with your details, then press Save button and this will create the configuration file.

See if this helps.

Regards,
Jordi
